### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Martian-Marvin**
This is my pull for exercise 2,  please  approve.

### CODE REVIEW

**Comment by Fieruz1** [comment]
ok

**Comment by Fieruz1** [comment]
Please Check

**Comment by Fieruz1** [comment]
Please check

**Review by Nacelik — APPROVED** [review]

**Comment by Nacelik** [comment]
I believe we need to commit into development and stage branches only, I'm not too sure though! :)

**Review by arianaluna — APPROVED** [review]

**Pull request merged**
